name: Ejercicio2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3          
      - name: Build docker image
        working-directory: ./hangman-front
        env:
          DOCKER_USER: "dmd10"
          DOCKER_REPOSITORY: "hangman-api"
          DOCKER_PASSWORD: "NuJVknQsPPxsp4zEKN6M"
        run: | 
          echo $DOCKER_USER $DOCKER_PASS
          image=$DOCKER_USER/$DOCKER_REPOSITORY:$(date +%s)
          docker login ghcr.io -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker build . --file Dockerfile --tag ghcr.io/$image
          docker push ghcr.io/$image
