name: Ejercicio2

on:
  push:
    branches:
      - "main"
    paths:
      - "hangman-front/**"
  workflow_dispatch:
    
  pull_request:
    branches: [ main ] 
    paths: [ 'hangman-front/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghrc.io
          username: "dmd10"
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        working-directory: ./hangman-front
        env:
          DOCKER_USER: "dmd10"
          DOCKER_REPOSITORY: "hangman-api"
        run: |
          image=ghcr.io/$DOCKER_USER/$DOCKER_REPOSITORY:$(date +%s)
          docker build . --file Dockerfile --tag $image
          docker push $image  


