name: Ejercicio2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.SECRET_TOKEN }}
      - name: Build docker image
        working-directory: ./hangman-front
        env:
          DOCKER_USER: "dmd10"
          DOCKER_REPOSITORY: "hangman-api"
          DOCKER_PASSWORD: "NuJVknQsPPxsp4zEKN6M"
        run: | 
          image=$DOCKER_USER/$DOCKER_REPOSITORY:$(date +%s)
          docker build . --file Dockerfile --tag ghcr.io/$image
          docker push ghcr.io/$image
