name: Ejercicio2

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: build-code
        path: hangman-front/dist/
    - name: Build and Push Docker Image
      working-directory: ./hangman-front
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_REPOSITORY: "hangman-front"
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: | 
        echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin
        image=$DOCKER_USER/$DOCKER_REPOSITORY:$(date +%s)
        docker build . --file Dockerfile.workflow --tag $image
        docker push $image
 
