name: Ejercicio2

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: "dmd10"
        password: "JVMWxzLrsRp8jQYVt_qu"
        
    - name: Build and Push Docker Image
      working-directory: ./hangman-front
      env:
        DOCKER_REPOSITORY: "hangman-front"
      run: | 
        image=$DOCKER_USER/$DOCKER_REPOSITORY:$(date +%s)
        docker build --tag $image .
        docker push $image
 
