name: Ejercicio2

on:
  push:
    branches:
      - "main"
    paths:
      - "hangman-front/**"
  workflow_dispatch:
    
  pull_request:
    branches: [ main ] 
    paths: [ 'hangman-front/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: "dmd10"
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build docker image
        working-directory: ./hangman-front
        env:
          DOCKER_USER: "dmd10"
          DOCKER_REPOSITORY: "hangman-api"
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: | 
          image=$DOCKER_USER/$DOCKER_REPOSITORY:$(date +%s)
          docker build . --file Dockerfile --tag $image
          docker push $image
        #  echo $DOCKER_PASSWORD | docker login ghcr.io -u dmd10 --password-stdin
 
