name: Ejercicio2

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and Push Docker Image
      working-directory: ./hangman-front
      env:
        DOCKER_USER: "dmd10"
        DOCKER_REPOSITORY: "hangman-front"
        DOCKER_PASSWORD: "*8auV!T.<T)H/E->Z]sErH'6M;sV%qF7H!s/mB57[o0h?KbtRt"
      run: | 
        echo $DOCKER_USER $DOCKER_PASSWORD
        echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin
        image=$DOCKER_USER/$DOCKER_REPOSITORY:$(date +%s)
        docker build --tag $image .
        docker push $image
 
